collections:
  about_pages:
    output: true
name: Freestate Gymnastics
url: "http://www.freestategymnastics.com"
split: "<!--split-->"
defaults:
  - scope:
      path: ""
      type: Text
    values:
      layout: default